# Site settings
title: 何昇邦的博客                     #你博客的标题
SEOTitle: 何昇邦的博客 | Heshengbang's Blog        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: [email protected]    
description: "This is Heshengbang's Blog welcome!"              #网站介绍
keyword: "JAVA, OPENSOURCE, 何昇邦, heshengbang, BLOG, JVM" #关键词
url: "https://github.com/tongheshang/tongheshang.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "说点装逼的话。。。"
sidebar-avatar:/img/avatar-by.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g

# SNS settings
RSS: false
weibo_username:     yunshixin
github_username:    tongheshang
twitter_username:   heshengbang
